[workspace]
members = [
    "aux-display",
    "draw",
    "embedded-graphics-gba",
    "gol4",
    "gol5",
    "keypad",
    "uart-echo",
]

[profile.release]
codegen-units = 1
debug = true
incremental = false
lto = true
