[workspace]
members = [
    "draw",
    "embedded-graphics-gba",
    "game-of-life",
    "gba",
    "keypad",
    "uart-echo",
]

[profile.release]
codegen-units = 1
debug = true
incremental = false
lto = true
