[config]
skip_core_tasks = true

[tasks.mkdir]
command = "mkdir"
args = ["-p", "../target"]

[tasks.crt0]
dependencies = ["mkdir"]
command = "arm-none-eabi-as"
args = ["../gba/crt0.s", "-o", "../target/crt0.o"]

[tasks.build-debug]
dependencies = ["crt0"]
toolchain = "nightly"
command = "cargo"
args = ["build"]

[tasks.build-release]
dependencies = ["crt0"]
toolchain = "nightly"
command = "cargo"
args = ["build", "--release"]

[tasks.build]
alias = "build-debug"

[tasks.objcopy]
dependencies = ["build-release"]
command = "arm-none-eabi-objcopy"
args = [
    "-O",
    "binary",
    "../target/thumbv4-none-agb/release/${CARGO_MAKE_CRATE_NAME}",
    "../target/${CARGO_MAKE_CRATE_NAME}.gba",
]

[tasks.run]
dependencies = ["objcopy"]
command = "mgba"
args = ["--log-level=16", "../target/${CARGO_MAKE_CRATE_NAME}.gba"]

[tasks.debug]
dependencies = ["build-debug"]
script = [
'''
mgba -g ../target/thumbv4-none-agb/debug/${CARGO_MAKE_CRATE_NAME} &
script -q /dev/null -c \
    "arm-none-eabi-gdb \
        ../target/thumbv4-none-agb/debug/${CARGO_MAKE_CRATE_NAME} \
        -ex 'target extended-remote :2345'"
'''
]

[tasks.default]
alias = "objcopy"
