[package]
name = "embedded-graphics-gba"
version = "0.1.0"
authors = ["Michael Mogenson <michael.mogenson@gmail.com>"]
edition = "2018"

[dependencies]
gba = { git = "https://github.com/rust-console/gba" }
embedded-graphics = "0.6.2"
