[package]
name = "embedded-graphics-gba"
version = "0.1.0"
authors = ["Michael Mogenson <michael.mogenson@gmail.com>"]
edition = "2018"

[dependencies]
embedded-graphics = "0.6.2"
gba = { path = "../gba" }
